import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read=(path)=>readFileSync(new URL('../site-src/'+path,import.meta.url),'utf8');
const app=read('app.js');
const chrome=read('app-chrome.js');
const html=read('index.html');
const css=read('css/product.css');
const landingCss=read('css/landing.css');
const searchCss=read('css/search.css');
const sw=read('sw.js');
const manifest=JSON.parse(read('manifest.webmanifest'));
const searchModeTest=readFileSync(new URL('./search-mode-smoke.mjs',import.meta.url),'utf8');

assert.ok(html.includes('id="mainLanding"'),'main landing missing');
assert.ok(html.includes('id="mainLocateBtn"'),'landing GPS action missing');
assert.ok(html.includes('id="mainManualBtn"'),'landing manual action missing');
assert.ok(html.includes('id="tripExplorer"'),'GEO CANVAS explorer missing');
assert.ok(html.includes('id="geoCanvas"'),'interactive geo canvas missing');
assert.ok(html.includes('id="geoTarget"'),'draggable geo target missing');
assert.ok(html.includes('id="geoLocationPopup"'),'geo location popup missing');
assert.ok(html.includes('id="geoSearchSheet"'),'geo AI search sheet missing');
assert.ok(html.includes('id="geoStartQuickGps"'),'geo current-position action missing');
assert.ok(html.includes('id="geoStartChange"'),'geo manual start action missing');
assert.ok(html.includes('id="aiInput"'),'AI input missing');
assert.ok(html.includes('id="aiSend"'),'AI search action missing');
assert.ok(html.includes('id="bottomNav"'),'bottom nav missing');
assert.ok(html.includes('data-tab="explore"'),'explore tab missing');
assert.ok(html.includes('data-tab="quest"'),'quest tab missing');
assert.ok(html.includes('data-tab="keep"'),'keep tab missing');
assert.ok(html.includes('data-tab="my"'),'my tab missing');
assert.ok(html.includes('id="questView"'),'quest view missing');
assert.ok(html.includes('id="keepView"'),'keep view missing');
assert.ok(html.includes('id="myView"'),'my view missing');
assert.ok(html.includes('id="activeTripIsland"'),'active course island missing');
assert.ok(html.includes('id="settingsModal"'),'settings modal missing');
assert.ok(html.includes('id="coursePicker"'),'course picker missing');
assert.ok(html.includes('id="mapModal"'),'map modal missing');
assert.ok(html.includes('id="routeCompareModal"'),'route compare modal missing');
assert.ok(html.includes('id="vehicleModal"'),'vehicle modal missing');
assert.ok(html.includes('id="userVehicleList"'),'vehicle list missing');
assert.ok(html.includes('id="addVehicleBtn"'),'vehicle add action missing');
assert.ok(html.includes('id="attendanceCalendar"'),'attendance calendar missing');
assert.ok(html.includes('id="tripHistoryList"'),'trip history missing');
assert.ok(html.includes('id="settingsGpsToggle"'),'GPS setting missing');
assert.ok(html.includes('id="settingsNoticeToggle"'),'notice setting missing');
assert.ok(html.includes('id="dataResetBtn"'),'data reset action missing');
assert.ok(html.includes('id="settingsAppResetBtn"'),'app reset action missing');
assert.ok(html.includes('id="settingsAppRemoveBtn"'),'app remove action missing');
assert.ok(html.includes('id="legalModal"'),'legal modal missing');
assert.ok(html.includes('id="settingsPrivacyBtn"'),'privacy action missing');
assert.ok(html.includes('id="settingsTermsBtn"'),'terms action missing');
assert.ok(html.includes('id="settingsOpenSourceBtn"'),'open-source action missing');
assert.ok(html.includes('id="settingsLocationBtn"'),'location disclosure action missing');
assert.ok(html.includes('id="privacyNotice"'),'privacy notice missing');
assert.ok(html.includes('id="tripSettingsModal"'),'trip settings modal missing');
assert.ok(html.includes('id="tripSettingsVehicle"'),'trip vehicle setting missing');
assert.ok(html.includes('id="tripSettingsFuelPrice"'),'trip fuel-price setting missing');
assert.ok(html.includes('id="tripSettingsApply"'),'trip settings apply action missing');
assert.ok(html.includes('id="topShareBtn"'),'top share action missing');
assert.ok(html.includes('id="tripSheet"'),'trip sheet missing');
assert.ok(html.includes('id="tripSheetBackdrop"'),'trip sheet backdrop missing');
assert.ok(html.includes('id="tripSheetStart"'),'trip sheet start action missing');
assert.ok(html.includes('id="tripSheetMap"'),'trip sheet map action missing');
assert.ok(html.includes('id="tripSheetRoute"'),'trip sheet route action missing');
assert.ok(html.includes('id="tripSheetCost"'),'trip sheet cost action missing');
assert.ok(html.includes('id="tripSheetWeather"'),'trip sheet weather action missing');
assert.ok(html.includes('id="tripSheetShare"'),'trip sheet share action missing');
assert.ok(html.includes('id="tripSheetClose"'),'trip sheet close action missing');
assert.ok(html.includes('id="keepCount"'),'KEEP badge missing');
assert.ok(html.includes('id="questCount"'),'QUEST badge missing');
assert.ok(html.includes('id="profileName"'),'profile name missing');
assert.ok(html.includes('id="profileLevel"'),'profile level missing');
assert.ok(html.includes('id="profileXp"'),'profile XP missing');
assert.ok(html.includes('id="profileProgress"'),'profile progress missing');
assert.ok(html.includes('id="profileBadge"'),'profile badge missing');
assert.ok(html.includes('id="attendanceStreak"'),'attendance streak missing');
assert.ok(html.includes('id="attendanceTotal"'),'attendance total missing');
assert.ok(html.includes('id="questPoints"'),'quest points missing');
assert.ok(html.includes('id="questCompleted"'),'quest completed count missing');
assert.ok(html.includes('id="tripCount"'),'trip count missing');
assert.ok(html.includes('id="tripDistance"'),'trip distance missing');
assert.ok(html.includes('id="sharedTripBanner"'),'shared trip banner missing');
assert.ok(html.includes('id="sharedTripUseBtn"'),'shared trip rebase action missing');
assert.ok(html.includes('id="routeCompareTitle"'),'route compare title missing');
assert.ok(html.includes('id="mapTitle"'),'map title missing');
assert.ok(html.includes('id="coursePickerTitle"'),'course picker title missing');
assert.ok(html.includes('id="settingsTitle"'),'settings title missing');
assert.ok(html.includes('id="vehicleModalTitle"'),'vehicle modal title missing');
assert.ok(html.includes('id="tripSettingsTitle"'),'trip settings title missing');
assert.ok(html.includes('id="legalTitle"'),'legal title missing');
assert.ok(html.includes('id="weatherNow"'),'weather status missing');
assert.ok(html.includes('id="trafficNow"'),'traffic status missing');
assert.ok(html.includes('id="providerNow"'),'provider status missing');
assert.ok(html.includes('id="updatedAt"'),'updated-at status missing');
assert.ok(html.includes('id="mapCanvas"'),'map canvas missing');
assert.ok(html.includes('id="routeCompareContent"'),'route compare content missing');
assert.ok(html.includes('id="routeCompareSummary"'),'route compare summary missing');
assert.ok(html.includes('id="coursePickerContent"'),'course picker content missing');
assert.ok(html.includes('id="keepList"'),'keep list missing');
assert.ok(html.includes('id="questList"'),'quest list missing');
assert.ok(html.includes('id="tripHistoryList"'),'trip history list missing');

const travelServiceSource=read('js/services/travel-service.js');
const geocodingSource=read('js/services/geocoding.js');
const linkedPlaceSource=read('js/ui/linked-place-search.js');
const geoExplorerSource=read('js/ui/geo-explorer.js');
const tripStoreSource=read('js/store/trip-store.js');
const searchControllerSource=read('js/controllers/search-controller.js');
assert.ok(travelServiceSource.includes("costLabel:vehicle.fuel==='electric'?'충전비':'연료비'"),'energy cost labels missing');
assert.ok(travelServiceSource.includes('reverseGeocode'),'reverse geocoder facade missing');
assert.ok(geocodingSource.includes('export async function reverseGeocode'),'GPS reverse geocoder missing');
assert.ok(geocodingSource.includes('PLACE_ALIASES'),'place alias resolver missing');
assert.ok(linkedPlaceSource.includes('initLinkedPlaceSearch'),'course-level CAFE/FOOD search missing');
assert.ok(geoExplorerSource.includes('initGeoExplorer'),'GEO CANVAS controller missing');
assert.ok(geoExplorerSource.includes('xyToGeo') && geoExplorerSource.includes('geoToXY'),'Korea map coordinate projection missing');
assert.ok(geoExplorerSource.includes('travelService.reverseGeocode'),'drag-end place analysis missing');
assert.ok(geoExplorerSource.includes('setPointerCapture'),'drag pointer capture missing');
assert.ok(!geoExplorerSource.includes('L.map('),'primary GEO CANVAS must not use Leaflet map tiles');
assert.ok(!app.includes('async function api('),'internal fake API router must be removed');
assert.ok(app.includes('createTravelService()'),'travel service facade must be composed in app.js');
assert.ok(!app.includes('const state={'),'flat global state declaration must be removed');
assert.ok(app.includes('createAppState'),'state store factory missing');
assert.ok(app.includes('createSearchController'),'search controller missing');
assert.ok(app.includes('createTripStore'),'trip store missing');
assert.ok(app.includes('createVehicleStore'),'vehicle store missing');
assert.ok(app.includes('createQuestStore'),'quest store missing');
assert.ok(app.includes('createUserStore'),'user store missing');
assert.ok(app.includes('initGeoExplorer'),'geo explorer app integration missing');
assert.ok(searchControllerSource.includes('handleAiSearch'),'AI search controller missing');
assert.ok(searchControllerSource.includes('travelService.recommend'),'AI search must use travel service');
assert.ok(tripStoreSource.includes('saveTrip'),'trip save action missing');
assert.ok(tripStoreSource.includes('recordTrip'),'trip history action missing');
assert.ok(searchModeTest.includes('extractSearchIntent'),'TRIP-only intent smoke missing');
assert.ok(chrome.includes('navigator.share'),'native share missing');
assert.ok(chrome.includes('settingsGpsToggle'),'GPS setting integration missing');
assert.ok(chrome.includes('settingsNoticeToggle'),'notice setting integration missing');
assert.ok(chrome.includes('serviceWorker'),'PWA service worker integration missing');
assert.ok(css.includes('.bottom-nav'),'bottom nav styles missing');
assert.ok(css.includes('.active-trip-island'),'active island styles missing');
assert.ok(searchCss.includes('.tq-geo-explorer'),'geo explorer styles missing');
assert.ok(searchCss.includes('.tq-geo-target'),'geo target styles missing');
assert.ok(landingCss.includes('.main-landing'),'landing styles missing');
assert.ok(sw.includes('CACHE_NAME'),'service worker cache missing');
assert.ok(manifest.display==='standalone','PWA display must be standalone');
assert.ok(Array.isArray(manifest.icons)&&manifest.icons.length>=2,'PWA icons missing');

console.log('TRIP QUEST v1.10 UI shell, GEO CANVAS, navigation, settings, and PWA checks passed');
