(()=>{
  'use strict';
  const $=s=>document.querySelector(s);
  const el=(tag,cls,html='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(html)n.innerHTML=html;return n};

  const VEHICLE_KEY='tq_vehicle_settings_v1';
  const VEHICLES={
    compact:{label:'경차',fuel:'gasoline',eff:14.0}, small:{label:'소형차',fuel:'gasoline',eff:13.2},
    midsize:{label:'중형차',fuel:'gasoline',eff:11.5}, suv:{label:'SUV',fuel:'gasoline',eff:10.2},
    van:{label:'승합차',fuel:'diesel',eff:9.0}, ev:{label:'전기차',fuel:'electric',eff:5.0}
  };
  const FUEL_LABEL={gasoline:'휘발유',diesel:'경유',lpg:'LPG',electric:'전기'};
  const ENERGY_DEFAULT={gasoline:1858,diesel:1843,lpg:1050,electric:347};
  let setupWaitingForLocation=false;

  function readVehicle(){try{return JSON.parse(localStorage.getItem(VEHICLE_KEY)||'null')}catch{return null}}
  function writeVehicle(v){localStorage.setItem(VEHICLE_KEY,JSON.stringify(v))}
  function forceVisibleMotion(scene){if(!scene||typeof scene.animate!=='function')return;scene.animate([{transform:'translate3d(-5px,-8px,0) scale(1.01)',filter:'brightness(.92)'},{transform:'translate3d(6px,8px,0) scale(1.025)',filter:'brightness(1.12)'},{transform:'translate3d(-5px,-8px,0) scale(1.01)',filter:'brightness(.92)'}],{duration:6200,iterations:Infinity,easing:'ease-in-out'});const core=scene.querySelector('.tq-core');core?.animate([{transform:'translate(-50%,-50%) rotate(45deg) scale(.92)'},{transform:'translate(-50%,-50%) rotate(225deg) scale(1.08)'},{transform:'translate(-50%,-50%) rotate(405deg) scale(.92)'}],{duration:9000,iterations:Infinity,easing:'linear'});scene.querySelectorAll('.tq-node').forEach((node,i)=>node.animate([{opacity:.2,transform:'rotate(45deg) scale(.7)'},{opacity:1,transform:'rotate(225deg) scale(1.45)'},{opacity:.2,transform:'rotate(405deg) scale(.7)'}],{duration:1800+i*180,iterations:Infinity,easing:'ease-in-out',delay:-i*240}))}
  function addCoverMotion(){const bg=$('.main-landing-bg');if(!bg)return;const existing=bg.querySelector('.tq-geo-scene');if(existing){forceVisibleMotion(existing);return}const scene=el('div','tq-geo-scene');scene.setAttribute('aria-hidden','true');scene.innerHTML='<div class="tq-orbit tq-orbit-a"></div><div class="tq-orbit tq-orbit-b"></div><div class="tq-orbit tq-orbit-c"></div><div class="tq-scan"></div><i class="tq-beam b1"></i><i class="tq-beam b2"></i><i class="tq-beam b3"></i><i class="tq-beam b4"></i><i class="tq-node n1"></i><i class="tq-node n2"></i><i class="tq-node n3"></i><i class="tq-node n4"></i><i class="tq-node n5"></i><i class="tq-node n6"></i><div class="tq-core"><span></span><b>AI</b></div>';bg.appendChild(scene);forceVisibleMotion(scene)}
  function showCover(){const landing=$('#mainLanding');if(!landing)return;landing.hidden=false;landing.classList.remove('leaving');document.body.classList.add('landing-open');addCoverMotion();window.scrollTo({top:0,behavior:'smooth'})}
  function scrollToTarget(s){$(s)?.scrollIntoView({behavior:'smooth',block:'start'})}

  function createVehicleSetup(){if($('#tqVehicleSetup'))return;const modal=el('div','tq-setup-overlay');modal.id='tqVehicleSetup';modal.hidden=true;modal.innerHTML=`<div class="tq-setup-card" role="dialog" aria-modal="true" aria-labelledby="tqSetupTitle"><div class="tq-setup-kicker">FIRST SETUP</div><h2 id="tqSetupTitle">차량을 설정하세요.</h2><p>이 값으로 이동거리의 예상 연료비·충전비와 통행료를 계산합니다.</p><div class="tq-setup-section"><label>차량 종류</label><div id="tqVehicleTypes" class="tq-choice-grid">${Object.entries(VEHICLES).map(([k,v])=>`<button type="button" data-vehicle="${k}">${v.label}</button>`).join('')}</div></div><div class="tq-setup-row"><label>동력원<select id="tqFuel"><option value="gasoline">휘발유</option><option value="diesel">경유</option><option value="lpg">LPG</option><option value="electric">전기</option></select></label><label><span id="tqEffLabel">연비</span><div class="tq-unit-input"><input id="tqEfficiency" type="number" min="1" max="30" step="0.1"><b id="tqEffUnit">km/L</b></div></label></div><div class="tq-setup-info"><span>에너지 가격</span><strong id="tqEnergyPrice">전국 평균 자동</strong><small>앱의 최신 평균 기준값을 자동 적용합니다.</small></div><label class="tq-check"><input id="tqTollDiscount" type="checkbox"><span>경차 통행료 할인 적용</span></label><button id="tqSetupSave" type="button" class="tq-setup-save">설정 완료</button><small class="tq-setup-foot">설정은 이 기기에 저장됩니다. 이후 설정 메뉴에서 변경할 수 있습니다.</small></div>`;document.body.appendChild(modal);
    const typeBox=$('#tqVehicleTypes'),fuel=$('#tqFuel'),eff=$('#tqEfficiency'),discount=$('#tqTollDiscount');
    const sync=()=>{const f=fuel.value;$('#tqEffLabel').textContent=f==='electric'?'전비':'연비';$('#tqEffUnit').textContent=f==='electric'?'km/kWh':'km/L';$('#tqEnergyPrice').textContent=f==='electric'?`평균 충전단가 ${ENERGY_DEFAULT[f].toLocaleString()}원/kWh`:`평균 ${FUEL_LABEL[f]} ${ENERGY_DEFAULT[f].toLocaleString()}원/L`};
    typeBox.onclick=e=>{const b=e.target.closest('[data-vehicle]');if(!b)return;typeBox.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));const d=VEHICLES[b.dataset.vehicle];fuel.value=d.fuel;eff.value=d.eff;discount.checked=b.dataset.vehicle==='compact';sync()};fuel.onchange=()=>{const selected=typeBox.querySelector('.selected')?.dataset.vehicle;const d=VEHICLES[selected]||VEHICLES.midsize;if(fuel.value==='electric')eff.value=5.0;else if(d.fuel===fuel.value)eff.value=d.eff;sync()};
    $('#tqSetupSave').onclick=()=>{const vehicle=typeBox.querySelector('.selected')?.dataset.vehicle;if(!vehicle){typeBox.classList.add('error');return}const efficiency=Number(eff.value);if(!Number.isFinite(efficiency)||efficiency<=0){eff.focus();return}const settings={vehicle,vehicleLabel:VEHICLES[vehicle].label,fuel:fuel.value,fuelLabel:FUEL_LABEL[fuel.value],efficiency,tollDiscount:discount.checked,energyPrice:ENERGY_DEFAULT[fuel.value],savedAt:new Date().toISOString()};writeVehicle(settings);applyVehicleSettings(settings);closeVehicleSetup();window.dispatchEvent(new CustomEvent('tripquest:vehicle-settings',{detail:settings}))};
  }
  function openVehicleSetup(){createVehicleSetup();const modal=$('#tqVehicleSetup'),saved=readVehicle();const key=saved?.vehicle||'compact';const d=VEHICLES[key]||VEHICLES.compact;modal.hidden=false;document.body.classList.add('tq-modal-open');const btn=modal.querySelector(`[data-vehicle="${key}"]`);btn?.click();if(saved){$('#tqFuel').value=saved.fuel||d.fuel;$('#tqEfficiency').value=saved.efficiency||d.eff;$('#tqTollDiscount').checked=!!saved.tollDiscount;$('#tqFuel').dispatchEvent(new Event('change'))}}
  function closeVehicleSetup(){$('#tqVehicleSetup')?.setAttribute('hidden','');document.body.classList.remove('tq-modal-open')}
  function applyVehicleSettings(s=readVehicle()){if(!s)return;const gas=$('#gasPrice');if(gas&&s.fuel!=='electric')gas.value=s.energyPrice||ENERGY_DEFAULT[s.fuel]||1858;document.documentElement.dataset.vehicle=s.vehicle||''}
  function watchFirstLocation(){const label=$('#originLabel');if(!label)return;const ready=()=>{const t=label.textContent.trim();return t&&t!=='위치를 아직 선택하지 않았습니다.'&&!/확인|검색|불러|실패|허용/.test(t)};const check=()=>{if(!setupWaitingForLocation||!ready())return;setupWaitingForLocation=false;if(!readVehicle())setTimeout(openVehicleSetup,180)};new MutationObserver(check).observe(label,{childList:true,subtree:true,characterData:true});$('#mainLocateBtn')?.addEventListener('click',()=>{setupWaitingForLocation=true;setTimeout(check,250)},{capture:true});check()}

  function addBottomNav(){if($('.tq-bottom-nav'))return;const nav=el('nav','tq-bottom-nav');nav.setAttribute('aria-label','앱 하단 메뉴');nav.innerHTML='<button type="button" data-tab="home" class="active"><i>⌂</i><span>홈</span></button><button type="button" data-tab="ai"><i>✦</i><span>AI 찾기</span></button><button type="button" data-tab="plan"><i>⌖</i><span>여행</span></button><button type="button" data-tab="settings"><i>⚙</i><span>설정</span></button>';document.body.appendChild(nav);const setActive=tab=>nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));nav.onclick=e=>{const b=e.target.closest('button');if(!b)return;const tab=b.dataset.tab;if(tab==='home'){setActive('home');showCover()}else if(tab==='ai'){setActive('ai');scrollToTarget('.ai-hero');$('#aiInput')?.focus({preventScroll:true})}else if(tab==='plan'){setActive('plan');scrollToTarget('#progress')}else if(tab==='settings'){setActive('settings');openVehicleSetup()}}}
  function enhanceTopbar(){const top=$('.topbar');if(!top||top.querySelector('.tq-top-label'))return;top.classList.add('tq-appbar');const label=el('div','tq-top-label','<small>TRIP QUEST</small><strong>여행 플래너</strong>');$('.brand')?.after(label);const share=$('#topShareBtn');if(share){share.setAttribute('aria-label','여행 공유');share.textContent='↗';share.classList.add('tq-icon-btn')}}
  function observeLanding(){const landing=$('#mainLanding'),nav=$('.tq-bottom-nav');if(!landing)return;const sync=()=>nav?.classList.toggle('cover-open',!landing.hidden);new MutationObserver(sync).observe(landing,{attributes:true,attributeFilter:['hidden','class']});sync()}
  function enforceCourseDetailOrder(){const panel=$('#courseDetailPanel'),map=panel?.querySelector('.course-route-map-card'),actions=panel?.querySelector('#courseActionButtons');if(panel&&map&&actions&&map.nextElementSibling!==actions)map.insertAdjacentElement('afterend',actions)}
  function observeCourseDetailOrder(){const panel=$('#courseDetailPanel');if(!panel)return;enforceCourseDetailOrder();new MutationObserver(()=>requestAnimationFrame(enforceCourseDetailOrder)).observe(panel,{childList:true,subtree:false})}
  function selectedManualCount(){return document.querySelectorAll('#categoryChoices button.selected').length}
  function addManualSearchButton(){const options=$('#manualOptions');if(!options||$('#manualSearchNow'))return;const wrap=el('div','manual-search-now');wrap.style.cssText='margin-top:18px;display:grid;gap:8px';wrap.innerHTML='<button id="manualSearchNow" class="btn primary" type="button" style="width:100%;min-height:56px">선택한 조건으로 검색하기 →</button><small id="manualSearchHint" style="color:#8e99a8;text-align:center"></small>';options.appendChild(wrap);const btn=$('#manualSearchNow'),hint=$('#manualSearchHint');const sync=()=>{const count=selectedManualCount();btn.disabled=count===0;hint.textContent=count?`취향 ${count}개 선택 · 현재 거리/방향 조건으로 검색`:'여행 취향을 1개 이상 선택하세요.'};options.addEventListener('click',()=>setTimeout(sync,0));sync();btn.onclick=async()=>{if(btn.disabled)return;const next=$('#nextBtn');if(!next)return;btn.disabled=true;btn.textContent='추천 조건 준비 중…';try{next.click();await new Promise(r=>setTimeout(r,120));btn.textContent='추천지 검색 중…';$('#nextBtn')?.click()}finally{setTimeout(()=>{btn.disabled=selectedManualCount()===0;btn.textContent='선택한 조건으로 검색하기 →'},900)}}}
  function parseWon(text){const n=Number(String(text||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}function parseKm(text){const n=Number(String(text||'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0}function fmtWon(n){return `${Math.round(n||0).toLocaleString('ko-KR')}원`}
  function estimateToll(km){const s=readVehicle();const one=Math.max(0,km/2);if(one<40)return 0;const base=(900+one*44.3)*2;return Math.max(0,Math.round((base*(s?.tollDiscount?.5:1))/100)*100)}
  function enhanceTripSummaryToll(){const summary=$('#tripSummary');if(!summary||!summary.querySelector('.metric-grid'))return;const metrics=[...summary.querySelectorAll('.metric')],find=l=>metrics.find(m=>m.querySelector('span')?.textContent.trim()===l),dm=find('왕복 거리'),tm=find('통행료')||find('예상 통행료'),total=find('교통비 합계'),fuel=find('기름값');if(!dm||!tm)return;const distance=parseKm(dm.querySelector('strong')?.textContent),estimated=estimateToll(distance),label=tm.querySelector('span'),value=tm.querySelector('strong');if(label)label.textContent='예상 통행료';if(value)value.textContent=estimated?`약 ${fmtWon(estimated)}`:'0원';if(total){const f=parseWon(fuel?.querySelector('strong')?.textContent);total.querySelector('strong').textContent=fmtWon(f+estimated)}}
  function observeTripSummary(){const summary=$('#tripSummary');if(!summary)return;new MutationObserver(()=>requestAnimationFrame(enhanceTripSummaryToll)).observe(summary,{childList:true,subtree:true,characterData:true});enhanceTripSummaryToll()}
  function runtimeHealthCheck(){document.querySelectorAll('#categoryChoices button,#directionChoices button,.progress-step').forEach(b=>b.type='button')}
  function bootChrome(){addCoverMotion();enhanceTopbar();addBottomNav();observeLanding();observeCourseDetailOrder();addManualSearchButton();observeTripSummary();createVehicleSetup();watchFirstLocation();applyVehicleSettings();runtimeHealthCheck();const footer=$('.app-version-footer');if(footer)footer.textContent='TRIP QUEST · v0.31';document.documentElement.classList.add('tq-chrome-ready')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootChrome,{once:true});else bootChrome();
})();